variable "region" {}
variable "manager_ami" {}
variable "manager_instance_type" {}
variable "worker_ami" {}
variable "worker_instance_type" {}
variable "cluster_public_key" {}
variable "cluster_user" {}
variable "cluster_private_key_path" {}
variable "subnet_id" {}
variable "subnet_cidr" {}
variable "pod_cidr" {}
variable "kubernetes_route_table_id" {}
variable "manager_security_group_id" {}
variable "worker_security_group_id" {}
variable "manager_elb_security_group_id" {}
variable "worker_elb_security_group_id" {}
variable "worker_count" {}
variable "manager_count" {}
variable "bastion_ip" {}
variable "app_tag" {}
